markdown: redcarpet
pygments: true

title_tag_text: GEEKmind. Mind a geek?
h1_tag_text: GEEKmind

exclude: ["config.ru", "Gemfile", "Gemfile.lock", "vendor", "Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
