markdown: redcarpet
highlighter: pygments

title_tag_text: GEEK!mind. Mind a geek?
h1_tag_text: GEEK!mind

exclude: ["config.ru", "Gemfile", "Gemfile.lock", "vendor", "Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
include: [".well-known", ".htaccess"]
